/*
 * Copyright (C) 2013 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package android.renderscript;


/**
 * Utility class for packing arguments and structures from Android system objects to
 * RenderScript objects.
 *
 * This class is only intended to be used to support the
 * reflected code generated by the RS tool chain.  It should not
 * be called directly.
 *
 * * @apiSince 11
 */

@SuppressWarnings({"unchecked", "deprecation", "all"})
public class FieldPacker {

/** @apiSince 11 */

public FieldPacker(int len) { throw new RuntimeException("Stub!"); }

/** @apiSince 18 */

public FieldPacker(byte[] data) { throw new RuntimeException("Stub!"); }

/** @apiSince 11 */

public void align(int v) { throw new RuntimeException("Stub!"); }

/** @apiSince 18 */

public void subalign(int v) { throw new RuntimeException("Stub!"); }

/** @apiSince 11 */

public void reset() { throw new RuntimeException("Stub!"); }

/** @apiSince 11 */

public void reset(int i) { throw new RuntimeException("Stub!"); }

/** @apiSince 11 */

public void skip(int i) { throw new RuntimeException("Stub!"); }

/** @apiSince 11 */

public void addI8(byte v) { throw new RuntimeException("Stub!"); }

/** @apiSince 18 */

public byte subI8() { throw new RuntimeException("Stub!"); }

/** @apiSince 11 */

public void addI16(short v) { throw new RuntimeException("Stub!"); }

/** @apiSince 18 */

public short subI16() { throw new RuntimeException("Stub!"); }

/** @apiSince 11 */

public void addI32(int v) { throw new RuntimeException("Stub!"); }

/** @apiSince 18 */

public int subI32() { throw new RuntimeException("Stub!"); }

/** @apiSince 11 */

public void addI64(long v) { throw new RuntimeException("Stub!"); }

/** @apiSince 18 */

public long subI64() { throw new RuntimeException("Stub!"); }

/** @apiSince 11 */

public void addU8(short v) { throw new RuntimeException("Stub!"); }

/** @apiSince 11 */

public void addU16(int v) { throw new RuntimeException("Stub!"); }

/** @apiSince 11 */

public void addU32(long v) { throw new RuntimeException("Stub!"); }

/** @apiSince 11 */

public void addU64(long v) { throw new RuntimeException("Stub!"); }

/** @apiSince 11 */

public void addF32(float v) { throw new RuntimeException("Stub!"); }

/** @apiSince 18 */

public float subF32() { throw new RuntimeException("Stub!"); }

/** @apiSince 11 */

public void addF64(double v) { throw new RuntimeException("Stub!"); }

/** @apiSince 18 */

public double subF64() { throw new RuntimeException("Stub!"); }

/** @apiSince 11 */

public void addObj(android.renderscript.BaseObj obj) { throw new RuntimeException("Stub!"); }

/** @apiSince 11 */

public void addF32(android.renderscript.Float2 v) { throw new RuntimeException("Stub!"); }

/** @apiSince 11 */

public void addF32(android.renderscript.Float3 v) { throw new RuntimeException("Stub!"); }

/** @apiSince 11 */

public void addF32(android.renderscript.Float4 v) { throw new RuntimeException("Stub!"); }

/** @apiSince 14 */

public void addF64(android.renderscript.Double2 v) { throw new RuntimeException("Stub!"); }

/** @apiSince 14 */

public void addF64(android.renderscript.Double3 v) { throw new RuntimeException("Stub!"); }

/** @apiSince 14 */

public void addF64(android.renderscript.Double4 v) { throw new RuntimeException("Stub!"); }

/** @apiSince 11 */

public void addI8(android.renderscript.Byte2 v) { throw new RuntimeException("Stub!"); }

/** @apiSince 11 */

public void addI8(android.renderscript.Byte3 v) { throw new RuntimeException("Stub!"); }

/** @apiSince 11 */

public void addI8(android.renderscript.Byte4 v) { throw new RuntimeException("Stub!"); }

/** @apiSince 11 */

public void addU8(android.renderscript.Short2 v) { throw new RuntimeException("Stub!"); }

/** @apiSince 11 */

public void addU8(android.renderscript.Short3 v) { throw new RuntimeException("Stub!"); }

/** @apiSince 11 */

public void addU8(android.renderscript.Short4 v) { throw new RuntimeException("Stub!"); }

/** @apiSince 11 */

public void addI16(android.renderscript.Short2 v) { throw new RuntimeException("Stub!"); }

/** @apiSince 11 */

public void addI16(android.renderscript.Short3 v) { throw new RuntimeException("Stub!"); }

/** @apiSince 11 */

public void addI16(android.renderscript.Short4 v) { throw new RuntimeException("Stub!"); }

/** @apiSince 11 */

public void addU16(android.renderscript.Int2 v) { throw new RuntimeException("Stub!"); }

/** @apiSince 11 */

public void addU16(android.renderscript.Int3 v) { throw new RuntimeException("Stub!"); }

/** @apiSince 11 */

public void addU16(android.renderscript.Int4 v) { throw new RuntimeException("Stub!"); }

/** @apiSince 11 */

public void addI32(android.renderscript.Int2 v) { throw new RuntimeException("Stub!"); }

/** @apiSince 11 */

public void addI32(android.renderscript.Int3 v) { throw new RuntimeException("Stub!"); }

/** @apiSince 11 */

public void addI32(android.renderscript.Int4 v) { throw new RuntimeException("Stub!"); }

/** @apiSince 11 */

public void addU32(android.renderscript.Long2 v) { throw new RuntimeException("Stub!"); }

/** @apiSince 11 */

public void addU32(android.renderscript.Long3 v) { throw new RuntimeException("Stub!"); }

/** @apiSince 11 */

public void addU32(android.renderscript.Long4 v) { throw new RuntimeException("Stub!"); }

/** @apiSince 14 */

public void addI64(android.renderscript.Long2 v) { throw new RuntimeException("Stub!"); }

/** @apiSince 14 */

public void addI64(android.renderscript.Long3 v) { throw new RuntimeException("Stub!"); }

/** @apiSince 14 */

public void addI64(android.renderscript.Long4 v) { throw new RuntimeException("Stub!"); }

/** @apiSince 14 */

public void addU64(android.renderscript.Long2 v) { throw new RuntimeException("Stub!"); }

/** @apiSince 14 */

public void addU64(android.renderscript.Long3 v) { throw new RuntimeException("Stub!"); }

/** @apiSince 14 */

public void addU64(android.renderscript.Long4 v) { throw new RuntimeException("Stub!"); }

/** @apiSince 18 */

public android.renderscript.Float2 subFloat2() { throw new RuntimeException("Stub!"); }

/** @apiSince 18 */

public android.renderscript.Float3 subFloat3() { throw new RuntimeException("Stub!"); }

/** @apiSince 18 */

public android.renderscript.Float4 subFloat4() { throw new RuntimeException("Stub!"); }

/** @apiSince 18 */

public android.renderscript.Double2 subDouble2() { throw new RuntimeException("Stub!"); }

/** @apiSince 18 */

public android.renderscript.Double3 subDouble3() { throw new RuntimeException("Stub!"); }

/** @apiSince 18 */

public android.renderscript.Double4 subDouble4() { throw new RuntimeException("Stub!"); }

/** @apiSince 18 */

public android.renderscript.Byte2 subByte2() { throw new RuntimeException("Stub!"); }

/** @apiSince 18 */

public android.renderscript.Byte3 subByte3() { throw new RuntimeException("Stub!"); }

/** @apiSince 18 */

public android.renderscript.Byte4 subByte4() { throw new RuntimeException("Stub!"); }

/** @apiSince 18 */

public android.renderscript.Short2 subShort2() { throw new RuntimeException("Stub!"); }

/** @apiSince 18 */

public android.renderscript.Short3 subShort3() { throw new RuntimeException("Stub!"); }

/** @apiSince 18 */

public android.renderscript.Short4 subShort4() { throw new RuntimeException("Stub!"); }

/** @apiSince 18 */

public android.renderscript.Int2 subInt2() { throw new RuntimeException("Stub!"); }

/** @apiSince 18 */

public android.renderscript.Int3 subInt3() { throw new RuntimeException("Stub!"); }

/** @apiSince 18 */

public android.renderscript.Int4 subInt4() { throw new RuntimeException("Stub!"); }

/** @apiSince 18 */

public android.renderscript.Long2 subLong2() { throw new RuntimeException("Stub!"); }

/** @apiSince 18 */

public android.renderscript.Long3 subLong3() { throw new RuntimeException("Stub!"); }

/** @apiSince 18 */

public android.renderscript.Long4 subLong4() { throw new RuntimeException("Stub!"); }

/** @apiSince 11 */

public void addMatrix(android.renderscript.Matrix4f v) { throw new RuntimeException("Stub!"); }

/** @apiSince 18 */

public android.renderscript.Matrix4f subMatrix4f() { throw new RuntimeException("Stub!"); }

/** @apiSince 11 */

public void addMatrix(android.renderscript.Matrix3f v) { throw new RuntimeException("Stub!"); }

/** @apiSince 18 */

public android.renderscript.Matrix3f subMatrix3f() { throw new RuntimeException("Stub!"); }

/** @apiSince 11 */

public void addMatrix(android.renderscript.Matrix2f v) { throw new RuntimeException("Stub!"); }

/** @apiSince 18 */

public android.renderscript.Matrix2f subMatrix2f() { throw new RuntimeException("Stub!"); }

/** @apiSince 11 */

public void addBoolean(boolean v) { throw new RuntimeException("Stub!"); }

/** @apiSince 18 */

public boolean subBoolean() { throw new RuntimeException("Stub!"); }

/** @apiSince 11 */

public final byte[] getData() { throw new RuntimeException("Stub!"); }
}

