/*
 * Copyright (c) 1997, 2007, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */



package javax.crypto.spec;


/**
 * This class specifies the set of parameters used with the Diffie-Hellman
 * algorithm, as specified in PKCS #3: <i>Diffie-Hellman Key-Agreement
 * Standard</i>.
 *
 * <p>A central authority generates parameters and gives them to the two
 * entities seeking to generate a secret key. The parameters are a prime
 * <code>p</code>, a base <code>g</code>, and optionally the length
 * in bits of the private value, <code>l</code>.
 *
 * <p>It is possible that more than one instance of parameters may be
 * generated by a given central authority, and that there may be more than
 * one central authority. Indeed, each individual may be its own central
 * authority, with different entities having different parameters.
 *
 * <p>Note that this class does not perform any validation on specified
 * parameters. Thus, the specified values are returned directly even
 * if they are null.
 *
 * @author Jan Luehe
 *
 * @see javax.crypto.KeyAgreement
 * @since 1.4
 * @apiSince 1
 */

@SuppressWarnings({"unchecked", "deprecation", "all"})
public class DHParameterSpec implements java.security.spec.AlgorithmParameterSpec {

/**
 * Constructs a parameter set for Diffie-Hellman, using a prime modulus
 * <code>p</code> and a base generator <code>g</code>.
 *
 * @param p the prime modulus
 * @param g the base generator
 * @apiSince 1
 */

public DHParameterSpec(java.math.BigInteger p, java.math.BigInteger g) { throw new RuntimeException("Stub!"); }

/**
 * Constructs a parameter set for Diffie-Hellman, using a prime modulus
 * <code>p</code>, a base generator <code>g</code>,
 * and the size in bits, <code>l</code>, of the random exponent
 * (private value).
 *
 * @param p the prime modulus
 * @param g the base generator
 * @param l the size in bits of the random exponent (private value)
 * @apiSince 1
 */

public DHParameterSpec(java.math.BigInteger p, java.math.BigInteger g, int l) { throw new RuntimeException("Stub!"); }

/**
 * Returns the prime modulus <code>p</code>.
 *
 * @return the prime modulus <code>p</code>
 * @apiSince 1
 */

public java.math.BigInteger getP() { throw new RuntimeException("Stub!"); }

/**
 * Returns the base generator <code>g</code>.
 *
 * @return the base generator <code>g</code>
 * @apiSince 1
 */

public java.math.BigInteger getG() { throw new RuntimeException("Stub!"); }

/**
 * Returns the size in bits, <code>l</code>, of the random exponent
 * (private value).
 *
 * @return the size in bits, <code>l</code>, of the random exponent
 * (private value), or 0 if this size has not been set
 * @apiSince 1
 */

public int getL() { throw new RuntimeException("Stub!"); }
}

